apiVersion: v1
kind: Namespace
metadata:
  name: argocd

# https://argo-cd.readthedocs.io/en/stable/getting_started/ に従っています。
# kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}' で外部から API にアクセスできるように。
