// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	PostTags string
	Posts    string
	Tags     string
	Users    string
}{
	PostTags: "post_tags",
	Posts:    "posts",
	Tags:     "tags",
	Users:    "users",
}
