version: "3.8"
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.26
    environment:
      MYSQL_DATABASE: dev
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/mysql-confd:/etc/mysql/conf.d
    ports:
      - "3306:3306"

  mysqldef:
    build:
      context: mysqldef
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_PORT: 3306
    volumes:
      - ./mysqldef/:/usr/local/bin
