version: "3.8"
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
