apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gin-gorm-tutorial
  name: golang-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: golang-api
  template:
    metadata:
      namespace: gin-gorm-tutorial
      labels:
        app: golang-api
    spec:
      serviceAccountName: main-ksa
      containers:
        - name: golang-api
          # 一旦 stg でイメージタグもベタ書きするが、後で動的になるように修正する
          image: asia-northeast1-docker.pkg.dev/playground-318023/stg-gin-gorm-tutorial-main/golang-api:v3
          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: db-auth
                  key: DSN
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: main-ksa
  namespace: gin-gorm-tutorial
  annotations:
    #  ここも stg ベタ書きになっているけど環境に合わせて動的にしたい
    iam.gke.io/gcp-service-account: stg-gin-gorm-tutorial-wi@playground-318023.iam.gserviceaccount.com
