apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  namespace: ingress-test
  name: cloud-cdn-backendconfig
spec:
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: false
