apiVersion: v1
kind: Service
metadata:
  namespace: ingress-test
  name: my-service
  labels:
    purpose: demonstrate-cdn
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"cloud-cdn-backendconfig"}}'
spec:
  type: NodePort
  selector:
    purpose: demonstrate-cdn
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
