apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.appName }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app: {{ .Values.appName }}
    spec:
      serviceAccountName: {{ .Values.mainServiceAccountName }}
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.gcpRegion }}-docker.pkg.dev/{{ .Values.gcpProjectID }}/{{ .Values.envPrefix }}-{{ .Release.Namespace }}-main/{{ .Values.appName }}:{{ .Values.dockerImageTag }}
          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: db-auth
                  key: DSN
          ports:
            - containerPort: 8080
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.23.1
          command:
            - "/cloud_sql_proxy"
            - "-instances={{ .Values.gcpProjectID }}:{{ .Values.gcpRegion }}:{{ .Values.envPrefix }}-{{ .Release.Namespace }}-master-instance1=tcp:5432"
          securityContext:
            runAsNonRoot: true
