apiVersion: v1
kind: ServiceAccount
metadata:
  name: main-ksa
  namespace: {{ .Values.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.envPrefix }}-{{ .Values.namespace }}-main@{{ .Values.gcpProjectID }}.iam.gserviceaccount.com
