apiVersion: v1
kind: ServiceAccount
metadata:
  name: main-ksa
  namespace: {{ .Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.envPrefix }}-{{ .Release.Namespace }}-main@{{ .Values.gcpProjectID }}.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-ksa
  namespace: {{ .Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.envPrefix }}-{{ .Release.Namespace }}-ex-sec@{{ .Values.gcpProjectID }}.iam.gserviceaccount.com
