apiVersion: v1
kind: Service
metadata:
  name: alb
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 80
      targetPort: 8080
  selector:
    app: {{ .Values.appName }}
