apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-proxy
  labels:
    app: envoy-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy-proxy
  template:
    metadata:
      name: envoy-proxy
      labels:
        app: envoy-proxy
    spec:
      containers:
        - name: envoy-proxy
          image: envoy-proxy
          imagePullPolicy: IfNotPresent
          command:
            - envoy
            - -c
            - /etc/envoy/envoy.yaml
          volumeMounts:
            - mountPath: /etc/envoy/envoy.yaml
              name: envoy-config
              readOnly: true
              subPath: envoy.yaml
      restartPolicy: Always
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-config
