apiVersion: v1
kind: Service
metadata:
  name: envoy-proxy
spec:
  selector:
    app: envoy-proxy
  ports:
    - port: 9901
      name: admin
    - port: 10000
      name: proxy
    - port: 10001
      name: grpc-server
  type: LoadBalancer
