envPrefix: prod
dockerImageTag: d4d0933137a5e90b7a347024c4b3325d2eae8910
# for https://github.com/external-secrets/kubernetes-external-secrets
kubernetes-external-secrets:
  serviceAccount:
    name: external-secrets-ksa
