envPrefix: stg
dockerImageTag: 9be3ab59439e65bf182751e645ea25d6b0be3c92
# for https://github.com/external-secrets/kubernetes-external-secrets
kubernetes-external-secrets:
  serviceAccount:
    name: external-secrets-ksa
