apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
    - image: my-nginx
      docker:
        dockerfile: ./docker/nginx/Dockerfile
    - image: my-api
      docker:
        dockerfile: ./docker/api/Dockerfile
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  local:
    push: false
    useBuildkit: true
    concurrency: 0
deploy:
  statusCheckDeadlineSeconds: 300
  kubeContext: docker-desktop
  kustomize:
    paths:
      - ./kubernetes/nginx
      - ./kubernetes/api-one
      - ./kubernetes/api-two

profiles:
  - name: nginx-demo
    build:
      artifacts:
        - image: my-nginx
          docker:
            dockerfile: ./docker/nginx/Dockerfile
        - image: my-api
          docker:
            dockerfile: ./docker/api/Dockerfile
    deploy:
      kustomize:
        paths:
          - ./kubernetes/nginx
          - ./kubernetes/api-one
          - ./kubernetes/api-two
