version: "3.8"

services:
  article_grpc:
    image: grpc/go
    tty: true
    stdin_open: true
    volumes:
      - ./article/:/go/article
    entrypoint: protoc ./article/article.proto --go_out=plugins=grpc:.

  article_db:
    platform: linux/x86_64
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
    volumes:
      - ./article/tmp/db/data:/var/lib/mysql
      - ./article/initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  article_migration:
    build:
      context: ./article
      dockerfile: docker/migration.dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./article/migrations/:/go/src/app/migrations
    # マイグレーションファイル作成コマンド: migrate create -ext sql -dir migrations/ -seq file_name
    command: sh -c "migrate -database mysql://root:password@tcp\(article_db:3306\)/dev -path migrations/ up && migrate -database mysql://root:password@tcp\(article_db:3306\)/test -path migrations/ up"
    depends_on:
      - article_db

  article_boiler:
    build:
      context: ./article
      dockerfile: docker/boiler.dockerfile
    tty: true
    stdin_open: true
    volumes:
      - .:/go/src/app
    depends_on:
      - article_db
