CREATE TABLE posts
(
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      varchar(250)              NOT NULL DEFAULT '',
    user_id    int REFERENCES users (id) NOT NULL,
    created_at timestamptz               NOT NULL DEFAULT current_timestamp,
    updated_at timestamptz               NOT NULL DEFAULT current_timestamp
);

ALTER TABLE posts
    ADD FOREIGN KEY (user_id) REFERENCES users (id);
