apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend1
  namespace: ingress-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend1
  template:
    metadata:
      labels:
        app: frontend1
      namespace: ingress-test
    spec:
      containers:
        - image: asia-northeast1-docker.pkg.dev/playground-318023/stg-ingress-frontend1/frontend1:latest
          name: frontend
          ports:
            - containerPort: 80
