apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ingress-test
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      namespace: ingress-test
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: asia-northeast1-docker.pkg.dev/playground-318023/stg-ingress-test-frontend/frontend
          ports:
            - containerPort: 80
