apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: stg-frontend1
  labels:
    cloud.googleapis.com/location: asia-northeast1
spec:
  template:
    spec:
      containers:
        - image: asia-northeast1-docker.pkg.dev/playground-318023/stg-next-deploy-frontend1/frontend1:latest
