apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rproxy
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      namespace: rproxy
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: asia-northeast1-docker.pkg.dev/playground-318023/stg-rproxy-nginx-proxy/nginx
          ports:
            - containerPort: 80
