apiVersion: v1
kind: Service
metadata:
  name: alb
  namespace: rproxy
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 80
      targetPort: 80
  selector:
    app: nginx
