apiVersion: v1
kind: Service
metadata:
  name: frontend1
  namespace: ingress-test
spec:
  type: ClusterIP
  selector:
    app: frontend1
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
