// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Municipalities string
	PostalCodes    string
	Prefectures    string
	TownAreas      string
}{
	Municipalities: "municipalities",
	PostalCodes:    "postal_codes",
	Prefectures:    "prefectures",
	TownAreas:      "town_areas",
}
