apiVersion: v1
kind: Service
metadata:
  name: frontend2
  namespace: ingress-test
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: frontend2
  type: ClusterIP
