// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlmodel

type Address struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type PostalCode struct {
	ID   string `json:"id"`
	Code string `json:"code"`
}
