version: "3.8"
services:
  db:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: development
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    tty: true
    stdin_open: true
    environment:
      DSN: "host=db user=postgres password=password dbname=development port=5432 sslmode=disable TimeZone=Asia/Tokyo"
    volumes:
      - .:/go/src/app
    ports:
      - 8080:8080
    depends_on:
      - db

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    tty: true
    stdin_open: true
    environment:
      DSN: "host=db user=postgres password=password dbname=test port=5432 sslmode=disable TimeZone=Asia/Tokyo"
      TEST_ENV: 1
      GIN_MODE: release
    volumes:
      - .:/go/src/app
    #  exec で少しでも早くテストが実行できるように、コンテナを終了させない
    command: sh -c "go test -v ./... && tail -f"
    depends_on:
      - db

  migration:
    build:
      context: .
      dockerfile: migration.dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./migrations/:/go/src/app/migrations
    environment:
      DEV_POSTGRESQL_URL: ${DEV_POSTGRESQL_URL}
      TEST_POSTGRESQL_URL: ${TEST_POSTGRESQL_URL}
    command: sh -c "migrate -database ${DEV_POSTGRESQL_URL} -path migrations up && migrate -database ${TEST_POSTGRESQL_URL} -path migrations up"
    depends_on:
      - db
