version: "3.8"
services:
  db:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: Asia/Tokyo
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    tty: true
    stdin_open: true
    volumes:
      - .:/go/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db

  test:
    build:
      context: .
      dockerfile: docker/test.dockerfile
    tty: true
    stdin_open: true
    command: go test -v ./...
    volumes:
      - .:/go/src/app
    depends_on:
      - db

  migration:
    build:
      context: .
      dockerfile: docker/migration.dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./migrations/:/go/src/app/migrations
    command: sh -c "migrate -database postgres://postgres:password@db:5432/postgres?sslmode=disable -path migrations up"
    depends_on:
      - db

  boiler:
    build:
      context: .
      dockerfile: docker/boiler.dockerfile
    tty: true
    stdin_open: true
    volumes:
      - .:/go/src/app
    depends_on:
      - db
