version: "3.8"

services:
  graph_db:
    platform: linux/x86_64
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
    volumes:
      - ./graphql/tmp/db/data:/var/lib/mysql
      - ./graphql/initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  graph_server:
    build:
      context: ./graphql
      dockerfile: docker/Dockerfile
      target: dev
    volumes:
      - ./graphql/:/go/src/app
    tty: true
    stdin_open: true
    environment:
      DB_HOST: graph_db
      DB_NAME: dev
      DB_USER: root
      DB_PASSWORD: password
      BOIL_DEBUG: true
      GOOGLE_APPLICATION_CREDENTIALS: /go/src/app/credentials/stg-firebase-service-account.json
    depends_on:
      - graph_db
    ports:
      - "8080:8080"

  # 本来このサービスは不要だが、 gqlgen を動かす時に必要ライブラリがインストールされておらず失敗する不具合があるので効率化のために設定
  # generate する時はこのサービスを利用して自動生成を行う
  gqlgen_generator:
    build:
      context: ./graphql
      dockerfile: docker/Dockerfile
      target: dev
    volumes:
      - ./graphql/:/go/src/app
    tty: true
    stdin_open: true
    command: sh -c "go get github.com/99designs/gqlgen/cmd@v0.14.0 && go run github.com/99designs/gqlgen && go mod tidy"

  graph_migration:
    build:
      context: ./graphql
      dockerfile: docker/migration.dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./graphql/migrations/:/usr/local/bin/migrations
    command: sh -c "./migrations/migration.sh"
    environment:
      DB_HOST: graph_db
      DB_USER: root
      DB_PASSWORD: password
      DB_PORT: 3306
      DB_NAME: dev
    depends_on:
      - graph_db

  graph_boiler:
    build:
      context: ./graphql
      dockerfile: docker/boiler.dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./graphql/:/go/src/app
    depends_on:
      - graph_db
