version: "3.8"

services:
  graph_db:
    platform: linux/x86_64
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
    volumes:
      - ./graphql/tmp/db/data:/var/lib/mysql
      - ./graphql/initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  graph_server:
    build:
      context: ./graphql
      dockerfile: docker/Dockerfile
      target: dev
    volumes:
      - ./graphql/:/go/src/app
    tty: true
    stdin_open: true
    environment:
      DB_HOST: graph_db
      DB_NAME: dev
      DB_USER: root
      DB_PASSWORD: password
      BOIL_DEBUG: true
      GOOGLE_APPLICATION_CREDENTIALS: /go/src/app/credentials/stg-firebase-service-account.json
    depends_on:
      - graph_db
    ports:
      - "8080:8080"

  graph_migration:
    build:
      context: ./graphql
      dockerfile: docker/migration.dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./graphql/migrations/:/go/src/app/migrations
    # マイグレーションファイル作成コマンド: migrate create -ext sql -dir migrations/ -seq file_name
    command: sh -c "migrate -database mysql://root:password@tcp\(graph_db:3306\)/dev -path migrations/ up && migrate -database mysql://root:password@tcp\(graph_db:3306\)/test -path migrations/ up"
    depends_on:
      - graph_db

  graph_boiler:
    build:
      context: ./graphql
      dockerfile: docker/boiler.dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./graphql/:/go/src/app
    depends_on:
      - graph_db
