version: "3.8"

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
    volumes:
      - ./graphql/tmp/db/data:/var/lib/mysql
      - ./graphql/initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  server:
    build:
      context: ./graphql
      dockerfile: docker/Dockerfile
      target: dev
    volumes:
      - ./graphql/:/go/src/app
    command: sh -c "go generate ./... & go run main.go"
    tty: true
    stdin_open: true
    environment:
      DB_HOST: db
      DB_NAME: dev
      DB_USER: root
      DB_PASSWORD: password
      BOIL_DEBUG: true
      GOOGLE_APPLICATION_CREDENTIALS: /go/src/app/credentials/stg-firebase-service-account.json
    depends_on:
      - db
    ports:
      - "8080:8080"

  migration:
    build:
      context: ./graphql
      dockerfile: docker/migration.dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./graphql/migrations/:/go/src/app/migrations
    # マイグレーションファイル作成コマンド: migrate create -ext sql -dir migrations/ -seq file_name
    # down バージョン sh -c "migrate -database mysql://root:password@tcp\(db:3306\)/dev -path migrations/ down && migrate -database mysql://root:password@tcp\(db:3306\)/test -path migrations/ down"
    command: sh ./migrations/migration.sh
    depends_on:
      - db

  test:
    build:
      context: ./graphql
      dockerfile: docker/test.dockerfile
    environment:
      DB_HOST: db
      DB_NAME: test
      DB_USER: root
      DB_PASSWORD: password
      TEST_ENV: 1
    tty: true
    stdin_open: true
    command: go test -v ./...
    volumes:
      - ./graphql/:/go/src/app
    depends_on:
      - db
