// Code generated by entc, DO NOT EDIT.

package test

const (
	// Label holds the string label denoting the test type in the database.
	Label = "test"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTest holds the string denoting the test field in the database.
	FieldTest = "test"
	// Table holds the table name of the test in the database.
	Table = "tests"
)

// Columns holds all SQL columns for test fields.
var Columns = []string{
	FieldID,
	FieldTest,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTest holds the default value on creation for the "test" field.
	DefaultTest bool
)
