name: docker build and staging deploy

defaults:
  run:
    shell: bash
    working-directory: ./gcp/cloud-run/next-deploy
on:
  push:
    paths:
      - "gcp/cloud-run/next-deploy/**"
      - ".github/workflows/cloud-run-ci.yml"

env:
  ENV_PREFIX: stg
  WORK_DIR: ./gcp/cloud-run/next-deploy

jobs:
  build:
    strategy:
      matrix:
        service:
          - frontend1
          - gin

    name: docker build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: list
        run: ls ${{ matrix.service }}
