name: create pull request

defaults:
  run:
    shell: bash
    working-directory: ./gcp/gke/gin-gorm-tutorial
on:
  push:

jobs:
  outputBranchName:
    runs-on: ubuntu-latest
    outputs:
      BRANCH_NAME: ${{ steps.output.outputs.BRANCH_NAME }}
    steps:
      - uses: actions/checkout@v2
      - name: echo commit message
        id: output
        # PRマージ時にデフォルトで作成されるコミットメッセージからブランチ名を力技で取得。。。
        # Merge pull request #9 from tatsuro-m/create-pull-request/stg/release → 'create-pull-request/stg/release'
        run: |
          COMMIT_MESSGE=$(git log -1 --pretty=format:"%s")
          echo "::set-output name=BRANCH_NAME::${COMMIT_MESSGE#*/}"

  createPullRequestForStg:
    # もっと良い方法があると思うがとりあえず。
    # マージコミットメッセージから取得したブランチ名が自動生成したブランチ名と一致するものならスキップする。
    # こうしないと手動でマージボタンを押した際に無限ループになるため。
    if: ${{ 'create-pull-request/stg/release' != needs.outputBranchName.outputs.BRANCH_NAME }}
    runs-on: ubuntu-latest
    needs: outputBranchName
    steps:
      - uses: actions/checkout@v2
      - name: Make changes to pull request
        run: |
          date +%s > report.txt
          echo "test" >> report.txt

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Create PR test
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: create-pull-request/stg/release
          base: main
          delete-branch: true
          title: '[Staging] Update Container Image'
          body: |
            Create PR test
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            update container image
            staging release
          assignees: tatsuro-m
          reviewers: tatsuro-m
          draft: false
