name: create pull request

defaults:
  run:
    shell: bash

env:
  WORK_DIR: ./gcp/gke/gin-gorm-tutorial/infrastructure/kubernetes/mychart

on:
  push:

jobs:
  outputBranchName:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORK_DIR }}
    outputs:
      BRANCH_NAME: ${{ steps.output.outputs.BRANCH_NAME }}
    steps:
      - uses: actions/checkout@v2
      - name: output branch name
        id: output
        # PRマージ時にデフォルトで作成されるコミットメッセージからブランチ名を力技で取得。。。
        # Merge pull request #9 from tatsuro-m/create-pull-request/stg/release → 'create-pull-request/stg/release'
        run: |
          COMMIT_MESSGE=$(git log -1 --pretty=format:"%s")
          echo "::set-output name=BRANCH_NAME::${COMMIT_MESSGE#*/}"

  createPullRequestForStg:
    # もっと良い方法があると思うがとりあえず。
    # マージコミットメッセージから取得したブランチ名が自動生成されたものならスキップする。条件は contain 関数で判断。
    if: ${{ !contains(needs.outputBranchName.outputs.BRANCH_NAME, 'create-pull-request/release') }}
    env:
      ENV: stg
    runs-on: ubuntu-latest
    needs: outputBranchName
    steps:
      - uses: actions/checkout@v2
      - name: chage docker image
        uses: mikefarah/yq@master
        with:
          cmd: IMAGE_TAG=${{ github.sha }} yq eval '.dockerImageTag = env(IMAGE_TAG)' -i ${{ env.WORK_DIR }}/${{ env.ENV }}-values.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Create PR test
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: create-pull-request/release/${{ env.ENV }}
          base: main
          delete-branch: true
          title: |
            [${{ env.ENV }}] Update Container Image
          body: |
            [${{ env.ENV }}] Update Container Image
            - Updated helm chart container image
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            update container image
            ${{ env.ENV }} release
          assignees: tatsuro-m
          reviewers: tatsuro-m
          draft: false

  createPullRequestForProd:
    if: ${{ !contains(needs.outputBranchName.outputs.BRANCH_NAME, 'create-pull-request/release') }}
    env:
      ENV: prod
    runs-on: ubuntu-latest
    needs: outputBranchName
    steps:
      - uses: actions/checkout@v2
      - name: chage docker image
        uses: mikefarah/yq@master
        with:
          cmd: IMAGE_TAG=${{ github.sha }} yq eval '.dockerImageTag = env(IMAGE_TAG)' -i ${{ env.WORK_DIR }}/${{ env.ENV }}-values.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Create PR test
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: create-pull-request/release/${{ env.ENV }}
          base: main
          delete-branch: true
          title: |
            [${{ env.ENV }}] Update Container Image
          body: |
            [${{ env.ENV }}] Update Container Image
            - Updated helm chart container image
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            update container image
            ${{ env.ENV }} release
          assignees: tatsuro-m
          reviewers: tatsuro-m
          draft: false
