name: build

defaults:
  run:
    shell: bash
    working-directory: ./gcp/ci-cd
on:
  push:
    paths:
      - "gcp/ci-cd/**"
#    branches-ignore:
#      - main

jobs:
  infrastructure:
    name: infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan
