name: production deploy

defaults:
  run:
    shell: bash
    working-directory: ./gcp/ci-cd
on:
  push:
    paths:
      - "gcp/ci-cd/infrastructure/production/**"
    branches:
      - main

jobs:
  infrastructure:
    name: infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gcp/ci-cd/infrastructure/production
    env:
      TF_VAR_billing_account_id: ${{ secrets.TF_VAR_BILLING_ACCOUNT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
