name: staging deploy

defaults:
  run:
    shell: bash
    working-directory: ./gcp/ci-cd
on:
  push:
    paths:
      - "gcp/ci-cd/infrastructure/staging/**"
    branches-ignore:
      - main

jobs:
  infrastructure:
    name: infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gcp/ci-cd/infrastructure/staging
    env:
      TF_VAR_billing_account_id: ${{ secrets.TF_VAR_BILLING_ACCOUNT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Install tfnotify
        id: install-tfnotify
        run: |
          sudo curl -fL -o tfnotify.tar.gz https://github.com/mercari/tfnotify/releases/download/v0.7.0/tfnotify_linux_amd64.tar.gz
          sudo tar -C /usr/bin -xzf ./tfnotify.tar.gz

      #  本番環境を apply したらどうなるかという差分を PR にコメントする
      - name: Terraform Plan
        id: plan
        run: terraform plan | tfnotify -config ../../../../.github/.tfnotify/github.yaml plan
        working-directory: ./gcp/ci-cd/infrastructure/production
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
