name: build

defaults:
  run:
    shell: bash
    working-directory: ./gcp/ci-cd
on: push
#  push:
#    paths:
#      - "gcp/ci-cd/**"
#    branches-ignore:
#      - main

jobs:
  infrastructure:
    name: infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gcp/ci-cd/infrastructure/staging

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Use gcloud CLI
        run: gcloud info

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1

      - name: Install tfnotify
        id: install-tfnotify
        run: |
          sudo curl -fL -o tfnotify.tar.gz https://github.com/mercari/tfnotify/releases/download/v0.7.0/tfnotify_linux_amd64.tar.gz
          sudo tar -C /usr/bin -xzf ./tfnotify.tar.gz

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan | tfnotify -config ../../../.github/.tfnotify/github.yaml plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
