apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
  labels:
    cloud.googleapis.com/location: asia-northeast1
  name: prod-frontend1
  namespace: '121819399873'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
    spec:
      containerConcurrency: 80
      containers:
        - image: asia-northeast1-docker.pkg.dev/playground-318023/prod-next-deploy-frontend1/frontend1:de3048c00d51b7f72fa030aa48f1f78b25a8bcd5
          env:
            - name: TEST
              value: 'true'
          ports:
            - containerPort: 3000
              name: http1
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
      serviceAccountName: prod-next-deploy-frontend1@playground-318023.iam.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100
